title: "Zampano's Courtyard"
author: "Zampano"
email: "zampano@tilde.team"
description: > # this means to ignore newlines until "baseurl:"
  Devblog &co.
baseurl: ""
lang: en
color_scheme: zenburn 
github_username: "zampano"

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
